apiVersion: v1
kind: Service
metadata:
  name: productservice-service
  namespace: default
spec:
  selector:
    app: productservice
  ports:
    - protocol: TCP
      port: 31001
      targetPort: 8080
      nodePort: 31001 
  type: LoadBalancer
  # loadBalancerIP: 172.22.39.97